# fly.toml app configuration file generated for pythonapps on 2024-01-01T22:48:18+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pythonapps"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "performance"
  cpus = 1
  memory_mb = 2048
